# on:
#   pull_request: # to update newly open PRs or when a PR is synced
#   check_suite: # to update all PRs upon a Check Suite completion
#     type: ['completed']
#   repository_dispatch:
#     types: [enable_merges, disable_merges]
  
# name: Branch Guard
# jobs:
#   branch-guard:
#     name: Branch Guard
#     if: github.event.check_suite.head_branch == 'main' || github.event.pull_request.base.ref == 'main'
#     runs-on: ubuntu-latest
#     steps:
#     - uses: cirrus-actions/branch-guard@v1.2
#       with:
#         appsToCheck: Are Merges Enabled?  # or any other App name (can be a comma separated list of names)
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}