on:
  pull_request: # to update newly open PRs or when a PR is synced
  check_suite: # to update all PRs upon a Check Suite completion
    type: ['completed']
  check_run:
  
name: Branch Guard
jobs:
  branch-guard:
    name: Branch Guard
    runs-on: ubuntu-latest
    steps:
    - uses: cirrus-actions/branch-guard@v1.2
      with:
        appsToCheck: Are Merges Enabled?  # or any other App name (can be a comma separated list of names)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}