---
name: Merges Enabled

on:
  pull_request: # to update newly open PRs or when a PR is synced
  check_suite: # to update all PRs upon a Check Suite completion
    type: ['completed']

jobs:
  merges-enabled:
    name: Are Merges Enabled?
    if: github.event.check_suite.head_branch == 'main' || github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: validate if merges are enabled
        shell: bash
        env:
          MERGES_ENABLED: ${{ secrets.MERGES_ENABLED }}
        run: |
          if [ "$MERGES_ENABLED" == "true" ]; then
              echo "Merges to main are enabled"
              exit 0
          else
              echo "Merges to main are not enabled"
              exit 1
          fi