---
name: Merges Enabled

on:
  pull_request:               # to update newly open PRs or when a PR is synced
  repository_dispatch:
    types: [enable_merges, disable_merges]

jobs:
  merges-enabled:
    name: Are Merges Enabled?
    runs-on: ubuntu-latest
    if: github.event.repository_dispatch.head_branch == 'main' || github.event.pull_request.base.ref == 'main'
    steps:
      - name: validate if merges are enabled
        shell: bash
        env:
          MERGES_ENABLED: ${{ secrets.MERGES_ENABLED }}
        run: |
          if [ "$MERGES_ENABLED" == "true" ]; then
              echo "Merges to main are enabled"
              exit 0
          else
              echo "Merges to main are not enabled"
              exit 1
          fi
      - uses: cirrus-actions/branch-guard@v1.2
        with:
          appsToCheck: Are Merges Enabled?  # or any other App name (can be a comma separated list of names)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}